version: '3.8'

services:
  app:
    container_name: toolbox-server
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    command: node app.js
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
